"""Adición de la columna de DNI en los estudiantes

Revision ID: 48c0fb4973d8
Revises: 442dc914c3ac
Create Date: 2025-06-18 11:30:53.469918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c0fb4973d8'
down_revision = '442dc914c3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dni')

    # ### end Alembic commands ###
